### ISSUE TITLE
images adding issues

### ISSUE THREAD

**Issue by PratibhaPatted** [PratibhaPatted/github-slideshow#6]
add images to github

**Comment by ayushikes** [comment]
i want to work on this issue can you please assign to me

**Comment by PratibhaPatted** [comment]
@ayushikes can you help me in adding some images or uml designs/diagrams to existing folder, from github and clone it to VS code.

**Comment by Divyansh1315** [comment]
Hey I can help you with this issue

**Comment by PratibhaPatted** [comment]
Hey @Divyansh1315 thank you, i got it how to add.

**Comment by Divyansh1315** [comment]
Oh that's great!!  You can try to close this issue if it's done so that it doesn't get mixed with your other new issues. It will be easy for others too who are visiting your Github issues section. 
All the best!
